dist: xenial
language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq apt-transport-https libmhash-dev python-docutils
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish63/script.deb.sh | sudo bash
  - sudo apt-get -q update
  - sudo apt-get install varnish varnish-dev
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra" &&
    make check VERBOSE=1
